name: food_hope
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # --- Let Flutter Auto-Solve These ---
  share_plus:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:

  # --- Safe / Unrelated Packages ---
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  http: ^1.2.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true